config/dol.yml:
    nintendo_hi_0.aw:
        addrs: [0x800c3140, 0x800cca40]
    __Creator__.bin:
        addrs: [0x800b05e8, 0x800b05f4]
    __DateTime__.bin:
        addrs: [0x800b05f4, 0x800b0608]