libultra/gfxprint/gfxprint_locate.c:
    .text: [0x8005B1EC, 0x8005B210]
libultra/gfxprint/gfxprint_locate8x8.c:
    .text: [0x8005B210, 0x8005B238]
# libforest/ReconfigBATs.c:
    # .text: [0x8007C070, 0x8005ae84]
