# ac_aprilfool_control/aPC_actor_dt.c: common_data is pure bs, 
    # .text: [0x805153f0, 0x8051542C]
zurumode/zerucheck_init.c:
    .text: [0x8040eb38, 0x8040EB50] 
zurumode/zerucheck_key_check.c:
    .text: [0x8040EB50, 0x8040EDA8]
zurumode/zurumode_cleanup.c:
    .text: [0x8040efc4, 0x8040f008]
# zurumode/zurumode_update.c:
    # .text: [0x8040EDA8 , 0x8040ee74] Won't really bother at the moment with this one.
m_random_field/mRF_MakePerfectBit.c:
    .text: [0x8050B1AC, 0x8050B1D4]
m_random_field/mRF_GetRandomStepMode.c:
    .text: [0x8050B284, 0x8050B2C0]
m_room_type/mRmTp_FtrItemNo2FtrIdx.c:
    .text: [0x803E7878, 0x803E78BC]

