name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/acreteam/ac-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [GAFE01_00] # GAFU01_00

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Normalize file mod times
    - name: Restore timestamps
      run: uv run https://raw.githubusercontent.com/MestreLion/git-tools/refs/tags/v2022.12/git-restore-mtime

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -a /orig .

    # Restore cached files
    - name: Cache build
      uses: actions/cache@v4
      with:
        path: |
          build
          .ninja_deps
          .ninja_log
          include/PR/abi.h
          include/PR/gbi.h
          include/PR/gs2dex.h
          include/PR/mbi.h
          include/PR/ultratypes.h
          include/compiler/gcc/stdlib.h
        key: ${{ runner.os }}-${{ matrix.version }}

    # Build the project
    - name: Build
      run: |
        python configure.py --map --version ${{ matrix.version }} \
            --binutils /binutils --compilers /compilers
        ninja all_source build/${{ matrix.version }}/progress.json \
            build/${{ matrix.version }}/report.json

    # Upload map files
    - name: Upload map
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_maps
        path: build/${{ matrix.version }}/**/*.MAP

    # Upload progress report
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/report.json
